#!/usr/bin/env python3
"""Extract Ghoulam actual GSUB glyphs at author's 11px native size.
Requires fonttools, freetype-py. Font (CC BY 4.0) by Imad AlFil / mloukhiyye.
No runtime font/Unicode dependency. Never independently center glyph artwork.
"""
from pathlib import Path
import argparse, hashlib, json
from fontTools.ttLib import TTFont
import freetype
p=argparse.ArgumentParser();p.add_argument('font');p.add_argument('--output',default='include/ghoulam_data.h');a=p.parse_args()
f=TTFont(a.font); face=freetype.Face(a.font);face.set_pixel_sizes(0,11)
cmap=f.getBestCmap();lookups=f['GSUB'].table.LookupList.Lookup
maps={tag:{} for tag in ['init','medi','fina']}
for r in f['GSUB'].table.FeatureList.FeatureRecord:
 if r.FeatureTag in maps:
  for i in r.Feature.LookupListIndex:
   for st in lookups[i].SubTable:maps[r.FeatureTag].update(st.mapping)
rows=[];names=['.notdef']
def add(g):
 if g not in names:names.append(g)
 return names.index(g)
for cp,g in sorted(cmap.items()):
 if not 0x621<=cp<=0x64a:continue
 if not f['glyf'][g].numberOfContours:continue
 forms=[g,maps['fina'].get(g,g),maps['init'].get(g,g),maps['medi'].get(g,g)]
 rows.append((cp,[add(n) for n in forms],int(g in maps['fina'] or cp==0x640),int(g in maps['init'] or cp in (0x640,0x649))))
lig=[]
for cp in [0x627,0x623,0x625,0x622]:
 found=[]
 for first in ['uni0644.init','uni0644.medi']:
  target=maps['fina'][cmap[cp]]
  matches=[l.LigGlyph for l in lookups[5].SubTable[0].ligatures[first] if l.Component==[target]]
  assert len(matches)==1
  found.append(add(matches[0]))
 lig.append((cp,found))
pixels=[];glyphs=[]
for name in names:
 gid=f.getGlyphID(name);face.load_glyph(gid,freetype.FT_LOAD_RENDER|freetype.FT_LOAD_TARGET_MONO)
 slot=face.glyph;b=slot.bitmap;offset=len(pixels)
 assert b.width<=16 and b.rows<=16,(name,b.width,b.rows)
 for y in range(b.rows):
  bits=0
  for x in range(b.width):
   if b.buffer[y*b.pitch+x//8]&(128>>(x%8)):bits|=1<<x
  pixels.append(bits)
 glyphs.append((offset,b.width,b.rows,slot.bitmap_left,11-slot.bitmap_top,round(slot.advance.x/64),gid))
 assert 0<=11-slot.bitmap_top and 11-slot.bitmap_top+b.rows<=16,(name,glyphs[-1])
out=['// GENERATED by tools/extract_ghoulam.py. Ghoulam Regular (c) 2025 Imad AlFil / mloukhiyye.',
'// CC BY 4.0 https://creativecommons.org/licenses/by/4.0/',
'// https://mloukhiyye.itch.io/ghoulam-arabic-pixel-art-font-version-1',
'// Converted actual unencoded GSUB forms to monochrome ROM rows, native 11px, baseline 11.',
'// Source SHA256 '+hashlib.sha256(Path(a.font).read_bytes()).hexdigest(),
'#pragma once','#include <cstdint>','namespace arabic {',
'struct Glyph { uint16_t offset; uint8_t width,height; int8_t left,top; uint8_t advance; uint16_t source_id; };',
'struct Letter { uint16_t code, form[4]; uint8_t prev,next; };',
'struct Ligature { uint16_t code, form[2]; };',
'inline constexpr Glyph glyphs[] = {']
out+=[' {%s}, // %s'%(','.join(map(str,g)),n) for n,g in zip(names,glyphs)]
out+=['};','inline constexpr uint16_t bitmap[] = {']
out+=[' '+','.join(hex(x) for x in pixels[i:i+16])+',' for i in range(0,len(pixels),16)]
out+=['};','inline constexpr Letter letters[] = {']
out+=[' {0x%x,{%s},%d,%d},'%(cp,','.join(map(str,forms)),prev,nxt) for cp,forms,prev,nxt in rows]
out+=['};','inline constexpr Ligature ligatures[] = {']
out+=[' {0x%x,{%s}},'%(cp,','.join(map(str,forms))) for cp,forms in lig]
out+=['};','}']
Path(a.output).write_text('\n'.join(out)+'\n')
print(json.dumps({'letters':len(rows),'glyphs':len(glyphs),'bitmap_bytes':len(pixels)*2,'max_advance':max(g[5] for g in glyphs),'glyph_names':names}))
