#!/usr/bin/env python3
"""Generate the Butano UI sprite font from gbamp3's 5x7 small font.

Compiles tools/gbamp3_small_font/small_font.c (verbatim gbamp3 v0.9.8 glyphs) with
the host C compiler and writes:
  graphics/ui_small_font_box.bmp / .json  8x16 sprite cells for '!'..'~' on a white box,
                                          for the overlays over book text
  include/ui_small_font.h                 per-character widths (6 px advance, as gbamp3)

Each cell: glyph in columns 1-5 with its cap height on rows 5-11 (descenders to
row 13) in palette index 1. Index 0 is transparent; the box font fills rows 3-14 of
every cell with index 2 (white), like gbamp3's message bar, so overlays drawn one
sprite per character read as one white label over book text ('~', blank in the
gbamp3 font, stands in for spaces there).
"""
import os
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIRST, LAST = 33, 126
CELL_W, CELL_H = 8, 16
GLYPH_X, GLYPH_Y = 1, 5
ADVANCE = 6


def glyph_rows():
    with tempfile.TemporaryDirectory() as tmp:
        exe = os.path.join(tmp, "small_font")
        subprocess.run([os.environ.get("CC", "cc"), "-O0", "-o", exe,
                        str(ROOT / "tools/gbamp3_small_font/small_font.c")], check=True)
        out = subprocess.run([exe], check=True, capture_output=True, text=True).stdout
    rows = {}
    for line in out.splitlines():
        values = [int(v) for v in line.split()]
        rows[values[0]] = values[1:]
    assert sorted(rows) == list(range(FIRST, LAST + 1))
    return rows


BOX_TOP, BOX_BOTTOM = 3, 14


def cell(bits, box):
    pixels = [[2 if box and BOX_TOP <= y <= BOX_BOTTOM else 0] * CELL_W for y in range(CELL_H)]
    for j, row in enumerate(bits):
        for k in range(5):
            if row & (16 >> k):
                pixels[GLYPH_Y + j][GLYPH_X + k] = 1
    return pixels


def write_bmp(path, pixels):
    height, width = len(pixels), len(pixels[0])
    palette = [(255, 0, 255), (0, 0, 0), (255, 255, 255)] + [(0, 0, 0)] * 13
    stride = (width + 3) & ~3
    image = b"".join(bytes(row) + b"\0" * (stride - width) for row in reversed(pixels))
    palette_bytes = b"".join(bytes((b, g, r, 0)) for r, g, b in palette)
    offset = 14 + 40 + len(palette_bytes)
    header = b"BM" + struct.pack("<IHHI", offset + len(image), 0, 0, offset)
    info = struct.pack("<IiiHHIIiiII", 40, width, height, 1, 8, 0, len(image), 3780, 3780, 16, 16)
    path.write_bytes(header + info + palette_bytes + image)


def main():
    rows = glyph_rows()
    assert not any(rows[ord("~")]), "'~' must stay blank: it is the box font's space"
    for name, box in (("ui_small_font_box", True),):
        pixels = []
        for c in range(FIRST, LAST + 1):
            pixels.extend(cell(rows[c], box))
        write_bmp(ROOT / f"graphics/{name}.bmp", pixels)
        (ROOT / f"graphics/{name}.json").write_text('{\n    "type": "sprite",\n    "height": 16\n}\n')
    widths = ",\n".join(f"    {ADVANCE},  // {c} {chr(c) if c > 32 else 'space'}"
                        for c in range(32, LAST + 1))
    (ROOT / "include/ui_small_font.h").write_text(
        "// Generated by tools/make_ui_small_font.py from gbamp3's 5x7 small font.\n"
        "#pragma once\n\n#include <cstdint>\n\nnamespace reader {\n\n"
        "// ' ' then '!'..'~': gbamp3 advances every character by 6 px.\n"
        f"constexpr int8_t ui_small_font_character_widths[] = {{\n{widths}\n}};\n\n}}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
